### ISSUE TITLE
Support several versions of MathComp by splitting zify.v

### ISSUE THREAD

**Issue by pi8027** [math-comp/mczify#11]
> > The interfaces for ordered types (such as porderType, latticeType, and orderType) and their overloaded operators (le, lt, min, max, meet, join, bottom, top, ...) are new in MathComp 1.11.0. 
>
> I see. Did you think about structuring your work differently, say having a separate file for the operators new in mathcomp 1.11 and then having collection files for mathcomp 1.10 and 1.11 which require those component files which are applicable? This might make it easier to maintain your work.
> 
> Do you think it would be possible to factor the differences between Coq versions into one file, so that the majority of the content in different Coq version branches would be identical?

_Originally posted by @MSoegtropIMC in https://github.com/pi8027/mczify/issues/9#issuecomment-658662776_

**Comment by pi8027** [comment]
I think supporting both MathComp 1.10 and 1.11 is doable in this way. It would also be nice to separate instances that require `coq-mathcomp-algebra` for packaging reasons. (But the instances for `divn`, `modn`, and `dvdn` require `algebra.intdiv` in the current implementation.)

In contrast, it is not possible (or difficult) to support different Coq versions. There was no pre hook mechanism for the zify tactic before Coq 8.13 and so I had to overwrite the `zify` tactic as follows in Coq 8.11 and 8.12. These internals are quite different. https://github.com/pi8027/mczify/blob/coq-8.11/theories/zify.v#L11-L13 https://github.com/pi8027/mczify/blob/coq-8.12/theories/zify.v#L13-L19

Also, Coq 8.12 forces us to zify boolean predicates to functions that return `Z`, but Coq 8.13 supports them in a better way. This makes instances for boolean predicates quite different.

**Comment by MSoegtropIMC** [comment]
@pi8027 : thanks for picking up this thought! I would say it is a good idea to first consider only the mathcomp version and component structure factorization and back port this to 8.12 and maybe 8.11 - let me know if I can help with one of these.  Then one should have a clearer view on what are the differences between different Coq versions and can still discuss if this can also be factored, or if this wouldn't give an advantage.

**Comment by pi8027** [comment]
I think that the conclusion was to have several branches and releases to support different versions of MathComp and Coq, and we can close this issue.
