### ISSUE TITLE
Release compatible with Coq 8.17

### ISSUE THREAD

**Issue by proux01** [math-comp/mczify#44]
@pi8027 could you please do a release (I can do the OPAM package if you want) so that we have a release compatible with Coq 8.17? (since 8.17 is in the CI, this should mostly be a matter of hitting the release button on github)

**Comment by pi8027** [comment]
Done. I suggest closing this issue after the release of the OPAM package. https://github.com/math-comp/mczify/releases/tag/1.3.0%2B1.12%2B8.13

**Comment by proux01** [comment]
Thanks!
Done: https://github.com/coq/opam-coq-archive/pull/2470

**Comment by pi8027** [comment]
Thanks!
